### ISSUE TITLE
Coordinates 2

### ISSUE THREAD

**Issue by radioman1511** [microp11/iridiumlive#13] opened 2019-12-24 13:55 UTC
Under Debian 9 and 10 the program does not work properly (coordinates wrong), if I start and debug in terminal with kdbg IridiumLive what a miracle, it works and the marker is set correctly, I don't know what the error is. Without the debugger kdbg it´s not work . The parser works well and the Udp packets it´s right. grts radioman1511
[IridiumLive.zip](https://github.com/microp11/iridiumlive/files/3998429/IridiumLive.zip)

**Comment by radioman1511** [comment] 2019-12-24 13:58
![grafik](https://user-images.githubusercontent.com/16371774/71415788-cf4d8700-265d-11ea-88f0-4cd7283d66e9.png)

**Comment by radioman1511** [comment] 2019-12-24 14:10
with kdbg IridiumLive
![grafik](https://user-images.githubusercontent.com/16371774/71416138-84cd0a00-265f-11ea-8831-96e9877d41b4.png)

**Comment by radioman1511** [comment] 2019-12-24 14:13
![grafik](https://user-images.githubusercontent.com/16371774/71416195-c1990100-265f-11ea-9f73-a0beb1729069.png)
IridiumLive running under kdbg-debugger no errors

**Comment by microp11** [comment] 2019-12-24 14:17
> Under Debian 9 and 10 the program does not work properly (coordinates wrong), if I start and debug in terminal with kdbg IridiumLive what a miracle, it works and the marker is set correctly, I don't know what the error is. Without the debugger kdbg it´s not work . The parser works well and the Udp packets it´s right. grts radioman1511
> [IridiumLive.zip](https://github.com/microp11/iridiumlive/files/3998429/IridiumLive.zip)

Add console output after the initial split. And run it real time. If the output is correct do the same until you find the part that fails. Replace the code that fails with a similar processing using substrings. Regular expressions even if you will.

**Comment by radioman1511** [comment] 2019-12-25 11:36
Next try , with Raspberry pi3 b debian buster same error no luck.grts radioman1511

**Comment by microp11** [comment] 2019-12-25 13:24
I tested on RPi 3b running Raspbian Buster Lite Minimal image based on Debian Buster. No issue.
Capture a few lines of log as it comes out of gr-iridium on the non working systems. Are the coordinates correct? If they are, capture a few lines of the same lines inside the sqlite db. We store the whole line, parsed and as is. Are the coordinates correct?
Have you tried my other suggestins on replacing the parser? There are so many ways to fix this.

**Comment by microp11** [comment] 2019-12-25 13:27
Duplicate of #12

**Comment by microp11** [comment] 2019-12-25 13:50
The code uses System.Convert.ToDouble(string-value) and the output is from a system whose current culture is en-US. I assume the culture on your system is different. You can try replacing the code with something like: Convert.ToDouble(string-value, System.Globalization.CultureInfo.InvariantCulture); 
use any of these: https://social.msdn.microsoft.com/Forums/vstudio/en-US/c0696afe-ad84-468b-a7a1-800bc45ab07b/culture-independent-converttodouble?forum=csharpgeneral
and let me know which one works. or let me know what is the culture on your system so i can try it as well. Thanks.

**Comment by microp11** [comment] 2019-12-25 13:53
I will also address this in the code. Will let you know when committed.

**Comment by microp11** [comment] 2019-12-25 14:11
Check this commit: https://github.com/microp11/iridiumlive/commit/49308a52a0805a3142b3b920b73e2da5b7253b3a

**Comment by radioman1511** [comment] 2019-12-25 14:59
Best job. Now the coordinates are passed correctly. Thank you, you are the best. merry christmas

**Comment by radioman1511** [comment] 2019-12-25 15:01
![grafik](https://user-images.githubusercontent.com/16371774/71447537-c75e1780-272f-11ea-89aa-d87dca777d2e.png)

**Comment by microp11** [comment] 2019-12-25 15:25
Thanks for the reports. Merry Christmas.

**Closed as completed by microp11** 2019-12-25 15:25 UTC
